import asyncio
import logging
from typing import AsyncGenerator
import yfinance as yf
from pydantic import BaseModel, Field
from typing import Optional
from src.config import settings
from openai import AsyncOpenAI

logger = logging.getLogger(__name__)

# ── Output schema ──────────────────────────────────────────────────────────────

class ConcentrationRisk(BaseModel):
    top_position_pct: float
    top_3_positions_pct: float
    flag: str  # "low", "moderate", "high", "critical"

class Performance(BaseModel):
    total_return_pct: Optional[float] = None
    annualized_return_pct: Optional[float] = None
    note: Optional[str] = None

class BenchmarkComparison(BaseModel):
    benchmark: str
    portfolio_return_pct: Optional[float] = None
    benchmark_return_pct: Optional[float] = None
    alpha_pct: Optional[float] = None
    note: Optional[str] = None

class Observation(BaseModel):
    severity: str  # "info", "warning", "critical"
    text: str

class PortfolioHealthReport(BaseModel):
    concentration_risk: ConcentrationRisk
    performance: Performance
    benchmark_comparison: BenchmarkComparison
    observations: list[Observation]
    disclaimer: str
    is_empty_portfolio: bool = False

DISCLAIMER = (
    "This analysis is generated by an AI system and is for informational purposes only. "
    "It does not constitute investment advice, a solicitation, or a recommendation to buy or sell any security. "
    "Past performance is not indicative of future results. Please consult a licensed financial advisor before making investment decisions."
)

# ── Market data helpers ────────────────────────────────────────────────────────

def _get_benchmark_for_user(user_context: dict) -> tuple[str, str]:
    """Pick an appropriate benchmark based on user's primary market."""
    currency = user_context.get("currency", "USD")
    country = user_context.get("country", "US")
    
    benchmark_map = {
        "IN": ("Nifty 50", "^NSEI"),
        "GB": ("FTSE 100", "^FTSE"),
        "DE": ("DAX", "^GDAXI"),
        "JP": ("Nikkei 225", "^N225"),
        "HK": ("Hang Seng", "^HSI"),
    }
    return benchmark_map.get(country, ("S&P 500", "^GSPC"))

def _fetch_benchmark_return(benchmark_ticker: str, period: str = "1y") -> Optional[float]:
    try:
        ticker = yf.Ticker(benchmark_ticker)
        hist = ticker.history(period=period)
        if hist.empty or len(hist) < 2:
            return None
        start_price = hist["Close"].iloc[0]
        end_price = hist["Close"].iloc[-1]
        return round((end_price - start_price) / start_price * 100, 2)
    except Exception as e:
        logger.warning(f"Could not fetch benchmark {benchmark_ticker}: {e}")
        return None

def _fetch_current_prices(tickers: list[str]) -> dict[str, float]:
    prices = {}
    for ticker in tickers:
        try:
            t = yf.Ticker(ticker)
            info = t.fast_info
            price = getattr(info, "last_price", None)
            if price:
                prices[ticker] = float(price)
        except Exception as e:
            logger.warning(f"Could not fetch price for {ticker}: {e}")
    return prices

# ── Core analysis ──────────────────────────────────────────────────────────────

def _analyse_portfolio(holdings: list[dict], user_context: dict) -> PortfolioHealthReport:
    """
    holdings: list of {ticker, quantity, avg_cost, current_value (optional)}
    user_context: {currency, country, risk_profile, ...}
    """
    
    # Empty portfolio — return BUILD-oriented response
    if not holdings:
        return PortfolioHealthReport(
            concentration_risk=ConcentrationRisk(top_position_pct=0, top_3_positions_pct=0, flag="n/a"),
            performance=Performance(note="No portfolio data — this is your starting point."),
            benchmark_comparison=BenchmarkComparison(
                benchmark="S&P 500",
                note="Once you make your first investment, we'll track your performance here."
            ),
            observations=[
                Observation(severity="info", text="Your portfolio is empty — now is the perfect time to start. Consider beginning with a low-cost index fund (e.g. a total market ETF) that gives you broad diversification from day one."),
                Observation(severity="info", text="A common starting framework: define your goal (retirement, emergency fund, wealth building), your time horizon, and how much volatility you can stomach — then pick instruments that match."),
                Observation(severity="info", text="Even a single diversified ETF like VTI, SCHD, or Nifty BeES (India) is a strong first allocation for a novice investor.")
            ],
            disclaimer=DISCLAIMER,
            is_empty_portfolio=True
        )
    
    # Compute position values
    positions = []
    for h in holdings:
        ticker = h.get("ticker", "").upper()
        qty = float(h.get("quantity", 0))
        avg_cost = float(h.get("avg_cost", 0))
        current_value = h.get("current_value")
        
        if current_value is None:
            current_value = qty * avg_cost  # fallback to cost basis if no current value
        
        positions.append({
            "ticker": ticker,
            "quantity": qty,
            "avg_cost": avg_cost,
            "current_value": float(current_value),
            "cost_basis": qty * avg_cost
        })
    
    # Try to enrich with live prices
    tickers = [p["ticker"] for p in positions if p["ticker"]]
    live_prices = _fetch_current_prices(tickers)
    for p in positions:
        if p["ticker"] in live_prices:
            p["current_value"] = live_prices[p["ticker"]] * p["quantity"]
    
    total_value = sum(p["current_value"] for p in positions)
    total_cost = sum(p["cost_basis"] for p in positions)
    
    if total_value == 0:
        total_value = total_cost  # prevent division by zero
    
    # Concentration risk
    sorted_positions = sorted(positions, key=lambda x: x["current_value"], reverse=True)
    top1_pct = round(sorted_positions[0]["current_value"] / total_value * 100, 1) if sorted_positions else 0
    top3_pct = round(sum(p["current_value"] for p in sorted_positions[:3]) / total_value * 100, 1) if len(sorted_positions) >= 3 else top1_pct
    
    if top1_pct >= 50:
        flag = "critical"
    elif top1_pct >= 30:
        flag = "high"
    elif top3_pct >= 70:
        flag = "moderate"
    else:
        flag = "low"
    
    # Performance
    total_return_pct = round((total_value - total_cost) / total_cost * 100, 2) if total_cost > 0 else None
    
    # Benchmark
    benchmark_name, benchmark_ticker = _get_benchmark_for_user(user_context)
    benchmark_return = _fetch_benchmark_return(benchmark_ticker)
    alpha = round(total_return_pct - benchmark_return, 2) if (total_return_pct is not None and benchmark_return is not None) else None
    
    # Build observations (surface the 1-2 things that matter most)
    observations = []
    
    top_holding = sorted_positions[0]["ticker"] if sorted_positions else "Unknown"
    
    if flag == "critical":
        observations.append(Observation(
            severity="critical",
            text=f"{top1_pct}% of your portfolio is in {top_holding}. This is extreme concentration — a single bad earnings report or sector downturn could cause severe damage. Consider trimming and diversifying."
        ))
    elif flag == "high":
        observations.append(Observation(
            severity="warning",
            text=f"{top1_pct}% of your portfolio is in {top_holding}. High concentration in one stock amplifies both gains and losses. A target of <20% per position is generally considered safer."
        ))
    
    if alpha is not None:
        if alpha > 0:
            observations.append(Observation(
                severity="info",
                text=f"Your portfolio is outperforming the {benchmark_name} by {alpha}% over the last year. Strong performance — but ensure this isn't driven entirely by your concentrated position."
            ))
        else:
            observations.append(Observation(
                severity="warning",
                text=f"Your portfolio is underperforming the {benchmark_name} by {abs(alpha)}% over the last year. A low-cost index fund tracking {benchmark_name} would have done better with less risk."
            ))
    
    if total_return_pct is not None and total_return_pct < -15:
        observations.append(Observation(
            severity="critical",
            text=f"Your portfolio is down {abs(total_return_pct):.1f}% from your cost basis. Review whether your positions still align with your original thesis before deciding to hold or cut losses."
        ))
    
    # Diversification across sectors hint
    if len(positions) < 5:
        observations.append(Observation(
            severity="info",
            text=f"You hold {len(positions)} position(s). Consider whether this provides adequate diversification across sectors, geographies, or asset classes for your risk tolerance."
        ))
    
    return PortfolioHealthReport(
        concentration_risk=ConcentrationRisk(
            top_position_pct=top1_pct,
            top_3_positions_pct=top3_pct,
            flag=flag
        ),
        performance=Performance(
            total_return_pct=total_return_pct,
            annualized_return_pct=None  # requires purchase dates; not always available
        ),
        benchmark_comparison=BenchmarkComparison(
            benchmark=benchmark_name,
            portfolio_return_pct=total_return_pct,
            benchmark_return_pct=benchmark_return,
            alpha_pct=alpha
        ),
        observations=observations,
        disclaimer=DISCLAIMER
    )

# ── LLM narrative generation ───────────────────────────────────────────────────

async def _generate_narrative(report: PortfolioHealthReport, user_query: str, user_context: dict) -> AsyncGenerator[str, None]:
    """Stream a plain-language narrative from the structured report."""
    
    if settings.openai_api_key == "mock-key":
        import asyncio
        await asyncio.sleep(0.5)
        mock_chunks = [
            "Based on my analysis, ", "your portfolio ", "shows a solid foundation. ",
            f"You have a total return of {report.performance.total_return_pct}% ",
            f"compared to your benchmark return of {report.benchmark_comparison.benchmark_return_pct}%. ",
            "However, you might want to review your concentration levels. ",
            f"\n\n---\n*{DISCLAIMER}*"
        ]
        for chunk in mock_chunks:
            yield chunk
            await asyncio.sleep(0.1)
        return
        
    client = AsyncOpenAI(api_key=settings.openai_api_key)
    
    risk_profile = user_context.get("risk_profile", "moderate")
    
    if report.is_empty_portfolio:
        system_msg = "You are Valura's AI co-investor. The user has an empty portfolio and is ready to start investing. Give warm, encouraging, practical guidance to a complete novice. Be specific and actionable. 3-4 short paragraphs max."
    else:
        system_msg = f"""You are Valura's AI co-investor speaking to a {risk_profile}-risk investor. 
You have just run a portfolio health check. Present the findings in plain language — no jargon without explanation.
Focus on the 1-2 most important things the user should know RIGHT NOW.
Be direct but not alarmist. End with one concrete next step.
3-4 short paragraphs. No bullet points in your main text."""
    
    report_summary = f"""
Concentration: {report.concentration_risk.flag} risk — top position is {report.concentration_risk.top_position_pct}%, top 3 are {report.concentration_risk.top_3_positions_pct}%
Performance: {report.performance.total_return_pct}% total return
vs {report.benchmark_comparison.benchmark}: {report.benchmark_comparison.benchmark_return_pct}% (alpha: {report.benchmark_comparison.alpha_pct}%)
Key flags: {[o.text for o in report.observations]}
"""
    
    user_msg = f"User asked: '{user_query}'\n\nHealth check results:\n{report_summary}\n\nProvide a clear, helpful summary for this user."
    
    stream = await client.chat.completions.create(
        model=settings.active_model,
        messages=[
            {"role": "system", "content": system_msg},
            {"role": "user", "content": user_msg}
        ],
        stream=True,
        max_tokens=500,
        temperature=0.4
    )
    
    async for chunk in stream:
        delta = chunk.choices[0].delta.content
        if delta:
            yield delta
    
    # Always append disclaimer at end
    yield f"\n\n---\n*{DISCLAIMER}*"

# ── Public interface ───────────────────────────────────────────────────────────

async def run_portfolio_health(
    query: str,
    user_context: dict,
    session_id: str
) -> AsyncGenerator[str, None]:
    """
    Main entry point. Yields SSE-compatible text chunks.
    user_context must contain 'holdings' list.
    """
    holdings = user_context.get("holdings", [])
    
    # Run analysis synchronously (CPU-bound, fast)
    report = _analyse_portfolio(holdings, user_context)
    
    # Yield structured metadata as first SSE event
    import json
    yield f"[STRUCTURED_DATA]{report.model_dump_json()}"
    yield "\n\n"
    
    # Stream narrative
    async for chunk in _generate_narrative(report, query, user_context):
        yield chunk
